---
title: "Decrypting the Alt Right"
subtitle: "An Analysis of Alt Right Online Discourse on Facebook"
author: "Fabio Votta"
date: "7 Dezember 2017"
output: pdf_document
---

# Abstract

**Decrypting the Alt Right: Using Topic Modelling and Sentiment Analysis to identify Alt Right commentary in media outlets**

The purpose of this research is to track Alt-Right discourse on Facebook and extract psychometric and linguistic features of their online commentary. More specifically, we aim to identify content that aligns with Alt-Right discussion patterns in the Facebook comment sections of relevant media outlets (e. g. CNN, Breitbart, FOX News etc.). With this research we hope to contribute to an automated content classification system and gain insights into how the Alt Right communicates online.

We gathered 1.3 Million comments from several Alt-Right network hubs and figureheads on Facebook (for example Infowars, Milo Yiannopolis, Mike Cernovich, Paul Jospeh Watson and others) over the course of one year (07.12.2016 - 07/12/2017). As a first step, we cleaned the data by removing common & irrelevant words and lemmatizing words. Next, we applied sentiment analysis to identify hateful and angry comments, leaving us with a dataset of polarized commentary. Moreover, we used topic modelling in order to pinpoint Alt Right talking points (for example "race realism", "anti-feminism", "fake news" and more) resulting in a text corpus where the relevant Alt Right narratives were succesfully isolated. 

We then proceed to map the cleaned Alt Right corpus on the comment sections of several news page outlets using a measure of cosinus similarity. We find that Alt Right discourse is mostly found on Fox News and Breitbart but can also be traced on less expected media outlets such as CNN and ABC.  

**Bächti Version**

**Decrypting [Was ist damit gemeint: den Begriff finde ich nicht so gut] the Alt Right: Using Topic Modelling and Sentiment Analysis to identify Alt Right commentary in media outlets**

This paper aims to track the “Alt Right” discourse on Facebook and extract psychometric and linguistic features of their online commentary. More specifically, we identify content that aligns with Alt Right narratives in the Facebook comment sections of relevant media outlets.

We gathered 1.3 Million comments from several Alt-Right figureheads on Facebook (e.g. Milo Yiannopolis, Mike Cernovich, Paul Joseph Watson and others) over the course of one year (07.12.2016 - 07/12/2017). As a first step, we cleaned the data by removing common words and using lemmatization. Next, we applied sentiment analysis to identify hateful comments, leaving us with a dataset of polarized commentaries. Moreover, we used topic modelling  to pinpoint Alt Right themes (for example "anti-feminism" and "anti-white racism") resulting in a text corpus where the relevant Alt Right narratives were successfully isolated. 
 
In a last step, we collected 1.1 million Facebook comments on several media outlets (e. g. CNN, Breitbart, FOX News etc.) over the same time range in order to compare them to our cleaned Alt Right corpus. We estimated the cosine similarity between the document term matrices to unravel the prevalence of Alt Right discourse on media outlets. We find that Alt Right narratives are mostly found on Fox News and Breitbart but they can also be found on mainstream media outlets such as CNN and ABC. Our results provide a first methodological attempt at classifying Alt Right content and its spread into mainstream media channels, which could be applied across different contexts and over time in the future.

by the means of sentiment analysis we identify hate speech

 between the different commentaries

analyze sentiments, topics to map them on major news outlets.

"coulter" = "695526053890545"

"cernovich" = "427302110732180"

"alexjones" = "6499393458"

"PJW" = "242174545810040"

"lauren" = "184795298567879"

"roaming" = "1213352768743538"

"bps" = "359762154043841"

"blairewhite" = "1136054926414603"

"disdain" = "1772552276096911"

"rebel" = "145634995501895"

"tommy" = "381971441938916"





## Media

"foxnews" = "15704546335"

"msnbc" = "273864989376427"

"breitbart" = "95475020353"

"cnn" = "5550296508"

"tucker" = "368557930146199"

"hannity" = "69813760388"


## Useful Links
- [fb page id](https://findmyfbid.com/success/95475020353)

## Alt - Right Personalities

- Milo Yiannopolis

https://www.facebook.com/myiannopoulos/

- Mike Cernovich

https://www.facebook.com/MikeCernovich/

- Alex Jones

https://www.facebook.com/AlexanderEmerickJones/

- Infowars

https://www.facebook.com/InfoWars-80256732576/?ref=br_rs

- Paul Joseph Watson

https://www.facebook.com/PaulJosephWatson/

- Disdain for Plebs

https://www.facebook.com/DfPWereShillz/

- Lauren Southern

https://www.facebook.com/LaurenCSouthern/

- Roaming Millenial

https://www.facebook.com/Roaming-Millennial-1213352768743538/?ref=br_rs

- Barbara4u2c

https://www.facebook.com/Barbara4u2c/

- Tara McCarthy

https://www.facebook.com/profile.php?id=100014041179050

- Murdoch Murdoch

https://www.facebook.com/Murdochx2/

- Mike Enoch

https://www.facebook.com/profile.php?id=100015425435298

- Black Pigeon Speaks

https://www.facebook.com/blackpigeonspeaks/

- Brittany Pettibone

https://www.facebook.com/brittany.a.pettibone

- Red Ice TV

https://www.facebook.com/RedIceCreations/

- Ann Coulter

https://www.facebook.com/OfficialAnnCoulter/

- Blaire White

https://www.facebook.com/ImBlaireWhite/?ref=br_rs

- Rebel Media

https://www.facebook.com/jointherebel/



## Media Outlets

- FOX News

https://www.facebook.com/FoxNews/

- MSNBC

https://www.facebook.com/msnbc/

- Breitbart

https://www.facebook.com/Breitbart/

- CNN

https://www.facebook.com/cnn/

- Tucker Carlson

https://www.facebook.com/TuckerCarlsonTonight/

- Sean Hannity

https://www.facebook.com/SeanHannity/

- Rachel Maddow

https://www.facebook.com/therachelmaddowshow/


VOX-Pol is convening a two-day workshop titled ‘Combating Online Extremism: State, Private Sector, and Civil Society Responses’ at the University of Oxford on 5 – 6 March, 2018.

The workshop seeks to explore the emerging responses from politicians, think tanks, technology companies, and civil society to the proliferation of extremism and hate online. The workshop will take a global, comparative approach with a view to evaluating approaches to combating online extremism, as well as its implications for governance.

As extreme speech on social media platforms has proliferated, online extremism has received a significant amount of attention from policymakers across the world. In this workshop, we consider how governments, civil society, and the private sector are responding to hate speech, cyber-bullying, and radicalisation online. These concerns have encouraged governments across the world to develop a variety of responses to online extremism, ranging from producing counter-narratives, the empowerment of ‘moderate’ voices, and calling on social media platforms to regulate content posted by their users. While these responses have multiplied, there have been very few rigorous evaluations of their methodologies and the forms of governance that shape them. This workshop seeks to highlight research which fills this gap, providing insight into the design of effective interventions and mapping changes to security practices in response to online hate and extremism.

The main topics of discussion for this workshop include:

Review of initiatives to counter hate speech, extremism, or radicalisation from governments and the private sector;
Technologies used to identify hate speech, extremism, or radicalisation and their use;
Comparison of regulations regarding hate speech and extremism across national contexts;
The responses and responsibilities of technology companies and internet service providers;
Evaluation of ‘positive’ approaches (e.g. counter-narratives, empowerment and resilience) and ‘negative’ approaches (e.g. removal of content, user suspension) to countering hate speech, extremism, and radicalisation online;
Inclusion of ethnic and religious minorities in countering hate speech, extremism, and radicalisation online;
Examination of the logics of governance and regulation that frame responses to online hate speech, extremism, and radicalisation.
We encourage interested scholars to submit 250-word abstracts on their research to workshop@voxpol.eu by 6 December 2017. We will send notifications of acceptance by 11 January 2018. We will work with participants during and after the workshop to develop contributions into a special issue or an edited volume. Please also include five key words and a short biography from the contributor along with the abstract.

# Alt Right keywords:

"cultural marxism"

"white genocide"

"sjw"

"cuck"

"dindu" "dindu nuffin"

"george soros" "soros"

"We must secure the existence of our people and a future for white children"

"((()))"

"anti white"

"Beta"

"Cuckservative"

"Cultural enrichment"

"Hatefact"

"Lügenpresse"

"Mainstream media"

"Mass immigration"

"Political Correctness" "pc"

"Postmodernism"

"Race Realism"

"Red pill"

"remove kebab" "kebab"

"cockroach"

"Safe space"

"Shekel"

"Shoah"

"oh vey"

"Soy Boy"

"snowflake"

"Triggered"

"virtue signal"

"White guilt"

"feminazi"

"White Knight"

"professional victim"

"mangina"

"Third Wave Feminism"

"joo"

# examples

The threat is Antifa, globalists, Muslim extremists , illuminati, George soros, elite, mainstream media!!! Love Jesus, Alex Jones & trump!!!	
