---
title: "R Notebook"
output: html_notebook
---


1. Type of Language
  * Vulgar Language
    + swearing
    + cursing
  * Hostile Language (against groups)
    + directed insults
    + stereotyping
    + humiliation 
    + derogatory
    + discrimination
  * Call for (physical) violence
    + mass deportation
    + Beat, Evict, Kill (Fantasy)
    + segregation
  
2. Irony (default no)

3. Talking Points
  * Political Antagonism 
    + Anti-Political Correctness (liberals are snowflakes)
  * Victumhood narrative
    + 
  * Sexism
    + Anti-Feminism
    + Traditional gender roles
    + Male dominate
    + Women are untrustworthy
  * Racism
    + white ethostate
    + segregation
    + white supremacy
    + blacks less intelligence (race realism)/ more criminal
    + dysgenics (Rassenschande)
  * Homophobia
    + degeneracy 
    + undermining traditional families
    + aids
    + decline of moral values
  * Anti-semitism
    + white genocide through mass immigration
    + Jews promote degeneracy
    + undermining nationalism (Jews are globalists).
    + 
  * Anti-Immigration
    + Anti-Muslim-Immigration (invasion)
    + Anti-Hispanic-Immigration (low IQ, + Haiti)
  
  
  
  
