---
title: "Scroll Rselenium"
output: html_notebook
---


```{r}
library(RSelenium)
rD <- rsDriver(verbose = F, port = as.integer(4111))

remDr <- rD$client
# remDr$close()
#remDr$open()
# remDr$setWindowSize(width = 800, height = 300)
```


```{r}
twitter <- "https://twitter.com/realDonaldTrump/status/956849981528379392"
rproject <- "https://www.r-project.org/about.html"

remDr$navigate(rproject)
remDr$screenshot(display = T)
```



works well only for r-project

* https://stackoverflow.com/questions/31901072/scrolling-page-in-rselenium

```{r}
remDr$navigate(twitter)
webElem <- remDr$findElement("css", "body")

webElem <- remDr$findElement("css", "#permalink-overlay-dialog > div.PermalinkOverlay-content > div > div > div.permalink-footer")
webElem$sendKeysToElement(list(key = "end"))
#webElem$screenshot()
```

```{r}
webElem$sendKeysToElement(list(key = "home"))
```

```{r}
webElem$sendKeysToElement(list(key = "down_arrow"))
#webElem$screenshot()
```



```{r}
webElem <- remDr$findElement("css", "#permalink-overlay-dialog > div.PermalinkOverlay-content > div > div > div.permalink-footer")
script <- "arguments[0].scrollIntoView(true);"
remDr$executeScript(script, args = list(webElem))
```


