---
title: "upload datasets"
output: html_notebook
---

```{r}
pacman::p_load(dplyr, ggplot2, googlesheets, openxlsx)
```

```{r}
shiny_token <- gs_auth()
```

```{r}
gs_load_up <- function(data, sheet_title){
  # speed up big data uploads by csv upload
  
  file_name <- "temp_data.xlsx"
  write.xlsx(data, file = file_name)

  gs_upload(
    file = file_name, 
    sheet_title = sheet_title
  )
  
  file.remove(file_name)
}

load("dataset1.Rdata")
gs_load_up(dataset1, "dataset1")
```



```{r}
#id <- gs_title("no_label")
#id %>% gs_browse()
#no_label <- gs_read(id)

init <- dataset1[1,] %>%
      mutate(
        identity = NA,
        moral = NA,
        elite = NA,
        left = NA,
        lang = NA,
        imm = NA,
        vict = NA,
        irony = NA,
        anti_fem = NA,
        race = NA,
        anti_sem = NA,
        anti_mus = NA,
        coder = NA,
        timestamp = NA
      )

## e.g., put it into .gitignore
altright_final <- gs_new(
  "altright_final", 
  input = init, 
  trim = T
)

sheet_key <- altright_final$sheet_key 
# new 
#"1RhTmAryGFNQFPTtBcivbBHz0udtQT1DHVDUwL-Cfpj4"

altright_final <- altright_final %>% 
  gs_add_row(input = init)
```


